name: ci 


on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-material pymdown-extensions mkdocs-glightbox

      - run: mkdocs gh-deploy --force
